# RAG Pipeline — ร้านฟ้าใหม่ (FahMai)
In-Memory Retrieval-Augmented Generation for Multiple Choice QA

---
**Pipeline Overview:**
1. Ingest `.md` knowledge base files into RAM
2. Vectorize documents with `BAAI/bge-m3`
3. Load `questions.csv` (id, question, choice_1…choice_10)
4. Cosine-similarity retrieval + trace logging
5. LLM generation via Ollama API
6. Fill `sample_submission.csv` template (id, ans) and save to `submission/`

## Cell 1 — Configuration Constants

In [7]:
# ============================================================
#  Configuration Constants
# ============================================================

KNOWLEDGE_BASE_DIR     = "../data/knowledge_base"
QUESTIONS_CSV_PATH     = "../data/questions.csv"
SAMPLE_SUBMISSION_PATH = "../data/sample_submission.csv"
SUBMISSION_DIR         = "../submission"
TRACE_LOG_PATH         = "./trace/trace_log.jsonl"

OLLAMA_API_URL         = "http://localhost:11434/api/generate"
LLM_MODEL_NAME         = "hf.co/nectec/pathumma-thaillm-8b-think-3.0.0-GGUF:Q8_0"
EMBEDDING_MODEL_NAME   = "Qwen/Qwen3-Embedding-0.6B"
TOP_K_RETRIEVAL        = 3

print("✅ Constants loaded.")

✅ Constants loaded.

## Cell 2 — Imports & Directory Setup

In [8]:
import os
import json
import re
import requests
import numpy as np
import pandas as pd
from pathlib import Path
from datetime import datetime
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from langchain_text_splitters import RecursiveCharacterTextSplitter

Path(TRACE_LOG_PATH).parent.mkdir(parents=True, exist_ok=True)
Path(SUBMISSION_DIR).mkdir(parents=True, exist_ok=True)

print("✅ Imports done. Directories ready.")

✅ Imports done. Directories ready.

## Cell 3 — Step 1: In-Memory Data Ingestion

In [9]:
# ============================================================
#  Step 1 — Load and CHUNK .md files
# ============================================================

# กำหนดขนาด Chunk (เช่น 500 ตัวอักษร, เผื่อส่วนที่ซ้อนทับกัน 50 ตัวอักษร)
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500, 
    chunk_overlap=100,
    separators=["\n\n## ", "\n\n", "\n", " "]
)

documents = []

for root, dirs, files in os.walk(KNOWLEDGE_BASE_DIR):
    for fname in sorted(files):
        if fname.endswith(".md"):
            filepath = os.path.join(root, fname)
            try:
                with open(filepath, "r", encoding="utf-8") as f:
                    content = f.read().strip()
                
                # หั่นเนื้อหาออกเป็นชิ้นเล็กๆ
                chunks = text_splitter.split_text(content)
                
                # เก็บแต่ละ Chunk แยกเป็น 1 Document
                for i, chunk in enumerate(chunks):
                    documents.append({
                        "filename": f"{os.path.relpath(filepath, KNOWLEDGE_BASE_DIR)} (Chunk {i+1})",
                        "content": chunk
                    })
            except Exception as e:
                print(f"⚠️  Could not read {filepath}: {e}")

print(f"✅ Loaded {len(documents)} chunks into memory.")

✅ Loaded 1337 chunks into memory.

## Cell 4 — Step 2: Vectorization (No Database)

In [10]:
# ============================================================
#  Step 2 — Embed all documents into a numpy matrix in RAM
# ============================================================

print(f"🔄 Loading embedding model: {EMBEDDING_MODEL_NAME} ...")
embed_model = SentenceTransformer(EMBEDDING_MODEL_NAME)

doc_texts = [f"Source: {doc['filename']}\n{doc['content']}" for doc in documents]

print(f"🔄 Encoding {len(doc_texts)} chunks...")
doc_embeddings = embed_model.encode(
    doc_texts,
    batch_size=16, # หาก RAM/VRAM เยอะ สามารถปรับเป็น 32 หรือ 64 เพื่อให้เร็วขึ้นได้
    show_progress_bar=True,
    normalize_embeddings=True  # unit-norm → cosine sim == dot product
)

print(f"✅ Document matrix shape: {doc_embeddings.shape}")

🔄 Loading embedding model: Qwen/Qwen3-Embedding-0.6B ...

Loading weights: 100%|██████████| 310/310 [00:00<00:00, 30451.16it/s]
'The read operation timed out' thrown while requesting HEAD https://huggingface.co/Qwen/Qwen3-Embedding-0.6B/resolve/main/special_tokens_map.json
Retrying in 1s [Retry 1/5].

🔄 Encoding 1337 chunks...

Batches: 100%|██████████| 84/84 [22:25<00:00, 16.02s/it]

✅ Document matrix shape: (1337, 1024)

## Cell 5 — Step 3: Load Questions & Submission Template

In [11]:
# ============================================================
#  Step 3 — Load questions.csv and sample_submission.csv
# ============================================================

# questions.csv: [id, question, choice_1 ... choice_10]
df_questions = pd.read_csv(QUESTIONS_CSV_PATH)
CHOICE_COLS  = [f"choice_{i}" for i in range(1, 11)]

missing_q = [c for c in ["id", "question"] + CHOICE_COLS if c not in df_questions.columns]
assert not missing_q, f"Missing columns in questions.csv: {missing_q}"
print(f"✅ Questions loaded: {len(df_questions)} rows")
display(df_questions.head(3))

# sample_submission.csv: [id, answer] — used as the output template
df_submission = pd.read_csv(SAMPLE_SUBMISSION_PATH)
assert "id" in df_submission.columns and "answer" in df_submission.columns, \
    "sample_submission.csv must have columns: id, answer"
print(f"\n✅ Sample submission template loaded: {len(df_submission)} rows")
display(df_submission.head(3))

✅ Questions loaded: 100 rows

,id,question,choice_1,choice_2,choice_3,choice_4,choice_5,choice_6,choice_7,choice_8,choice_9,choice_10
0,1,Watch S3 Ultra กันน้ำได้กี่ ATM ครับ,3 ATM,IP68,5 ATM,IP67,10 ATM,20 ATM,IPX8,1 ATM,ไม่มีข้อมูลนี้ในฐานข้อมูล,คำถามนี้ไม่เกี่ยวข้องกับฐานข้อมูลสินค้า
1,2,ปากกา SaiFah Pen Gen 2 ราคาเท่าไหร่คะ,"2,990 บาท","4,490 บาท","1,990 บาท","4,990 บาท","3,490 บาท","2,490 บาท","3,990 บาท","5,490 บาท",ไม่มีข้อมูลนี้ในฐานข้อมูล,คำถามนี้ไม่เกี่ยวข้องกับฐานข้อมูลสินค้า
2,3,หูฟัง HeadPro X1 ใช้ Bluetooth เวอร์ชันอะไรคะ,Bluetooth 5.0,Bluetooth 5.3,Bluetooth 5.4,Bluetooth 4.2,Bluetooth 5.2,Bluetooth 5.1,Bluetooth 4.0,Bluetooth 5.5,ไม่มีข้อมูลนี้ในฐานข้อมูล,คำถามนี้ไม่เกี่ยวข้องกับฐานข้อมูลสินค้า

✅ Sample submission template loaded: 100 rows

   id  answer
0   1       1
1   2       1
2   3       1

In [12]:
df_questions.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         100 non-null    int64
 1   question   100 non-null    str
 2   choice_1   100 non-null    str
 3   choice_2   100 non-null    str
 4   choice_3   100 non-null    str
 5   choice_4   100 non-null    str
 6   choice_5   100 non-null    str
 7   choice_6   100 non-null    str
 8   choice_7   100 non-null    str
 9   choice_8   100 non-null    str
 10  choice_9   100 non-null    str
 11  choice_10  100 non-null    str
dtypes: int64(1), str(11)
memory usage: 9.5 KB

## Cell 6 — Helper Functions

In [16]:
# ============================================================
#  Helper Functions (Upgraded Version 🚀)
# ============================================================

def retrieve_top_k(question: str, max_k: int = 4, threshold: float = 0.45) -> list[dict]:
    """
    Dynamic Retrieval: Embeds the question and returns documents 
    that pass the similarity threshold, up to a maximum of max_k.
    """
    q_vec  = embed_model.encode([question], normalize_embeddings=True)
    scores = cosine_similarity(q_vec, doc_embeddings)[0]  # shape (n_docs,)
    
    # Sort from highest score to lowest, taking the top max_k
    top_indices = np.argsort(scores)[::-1][:max_k]
    
    results = []
    for i in top_indices:
        score = float(scores[i])
        
        # DYNAMIC LOGIC: Only keep the document if its score is above the threshold
        if score >= threshold:
            results.append({
                "filename": documents[i]["filename"],
                "content":  documents[i]["content"],
                "score":    score
            })
            
    # SAFETY NET: What if the question is tricky and ALL scores are below the threshold?
    # We still want to give the LLM the absolute closest match to try and figure it out.
    if len(results) == 0:
        best_idx = top_indices[0]
        results.append({
            "filename": documents[best_idx]["filename"],
            "content":  documents[best_idx]["content"],
            "score":    float(scores[best_idx])
        })
        
    return results

def build_prompt(question: str, choices: list[str], retrieved_docs: list[dict]) -> str:
    """Build a highly detailed and strictly constrained Thai RAG prompt."""
    
    context = "\n\n---\n\n".join(
        f"[{doc['filename']}]\n{doc['content']}" for doc in retrieved_docs
    )
    choice_lines = "\n".join(f"{i+1}. {c}" for i, c in enumerate(choices))
    
    return f"""คุณคือ AI ผู้ช่วยอัจฉริยะระดับสูงของร้านฟ้าใหม่ (FahMai) ผู้ทำหน้าที่ผู้ประเมินข้อสอบแบบปรนัย (Multiple Choice)
    คำสั่งสูงสุดของคุณคือ: "ต้องตอบคำถามโดยอ้างอิงหลักฐานจาก [เอกสารอ้างอิง] ที่แนบมาให้เท่านั้น ห้ามใช้ความรู้เดิม ห้ามคิดไปเอง และห้ามเดาเด็ดขาด"

    [เอกสารอ้างอิง]
    {context}

    [คำถาม]
    {question}

    [ตัวเลือก]
    {choice_lines}

    [กฎการวิเคราะห์และข้อกำหนดที่ต้องปฏิบัติตามอย่างเคร่งครัด]
    1. ขั้นตอนการวิเคราะห์ (ภายในแท็ก <think>):
    - อ่านคำถามและดึงคีย์เวิร์ดสำคัญ
    - ค้นหาคีย์เวิร์ดเหล่านั้นใน [เอกสารอ้างอิง] แบบคำต่อคำ
    - หากพบข้อมูล: ให้นำข้อมูลนั้นมาเทียบกับ [ตัวเลือก] เพื่อหาข้อที่มีความหมายตรงกันที่สุดเพียง 1 ข้อ
    - หากไม่พบข้อมูล: หากอ่านเอกสารทั้งหมดแล้วไม่มีคำตอบ ห้ามพยายามเดา ให้เลือกตัวเลือกที่มีความหมายว่า "ไม่มีข้อมูลนี้ในฐานข้อมูล" ทันที

    2. การจัดการความยาว (ภายในแท็ก <think>):
    - จงเขียนสรุปการคิดให้ "สั้น กระชับ และตรงประเด็นที่สุด" (เช่น "ไฟล์ X ระบุว่าราคา 1,990 บาท ตรงกับตัวเลือก 3")
    - ห้ามเขียนเรียงความยาวๆ เพื่อป้องกันปัญหา Token Limit ทะลุ

    3. กฎการตอบผลลัพธ์สุดท้าย (ภายนอกแท็ก <think>):
    - บรรทัดสุดท้ายของคำตอบ จะต้องเป็นคำว่า "คำตอบ: " ตามด้วย "เลขโดด (1-10)" เท่านั้น
    - ห้ามใส่สัญลักษณ์ ห้ามใส่วงเล็บ ห้ามทวนคำถาม และห้ามพิมพ์ข้อความใดๆ ต่อท้ายตัวเลขโดยเด็ดขาด

    [รูปแบบผลลัพธ์ที่คุณต้องสร้าง (บังคับ)]
    <think>""" 

def call_ollama(prompt: str) -> str:
    """POST prompt to Ollama and return the raw response text."""
    payload = {
        "model": LLM_MODEL_NAME, 
        "prompt": prompt, 
        "stream": False,
        "options": {
            "num_ctx": 8192,
            "num_predict": 2048,
            "temperature": 0.1,
            "top_p": 0.9,
            "repeat_penalty": 1.15
        }
    }
    try:
        resp = requests.post(OLLAMA_API_URL, json=payload, timeout=600)
        resp.raise_for_status()
        
        raw = resp.json().get("response", "")
        
        # เนื่องจากเราบังคับเปิดแท็ก <think> ไปใน Prompt แล้ว
        # ผลลัพธ์ที่ได้กลับมามักจะไม่มี <think> เปิดแล้ว เราจึงประกอบร่างให้สมบูรณ์เพื่อง่ายต่อการ parse
        return "<think>\n" + raw 

    except Exception as e:
        print(f"  ⚠️ Ollama API Error: {e}")
        return ""

def extract_think(raw: str) -> str:
    """Extract content inside <think>...</think> tags."""
    if not raw: return ""
    m = re.search(r"<think>(.*?)</think>", raw, re.DOTALL | re.IGNORECASE)
    return m.group(1).strip() if m else ""

def extract_final_answer(raw: str) -> str:
    """Extract the text after </think> or after the word 'คำตอบ:'."""
    if not raw: return ""
    
    # 1. ตัด <think>...</think> ทิ้ง
    clean = re.sub(r"<think>.*?</think>", "", raw, flags=re.DOTALL | re.IGNORECASE).strip()
    
    # 2. ค้นหาคำว่า "คำตอบ:" แล้วดึง *เฉพาะตัวเลข* ชุดแรกที่เจอ
    m = re.search(r"คำตอบ\s*:\s*.*?(\d+)", clean)
    if m:
        return m.group(1).strip()
        
    # 3. Fallback: ถ้าไม่มีแพทเทิร์น ให้พยายามหาตัวเลขในบรรทัดสุดท้าย
    lines = [l.strip() for l in clean.splitlines() if l.strip()]
    if lines:
        last_line = lines[-1]
        digit_match = re.search(r"(\d+)", last_line)
        if digit_match:
            return digit_match.group(1)
        return last_line
    return clean

def append_trace(record: dict):
    """Append one JSON record to the trace log (JSONL format)."""
    with open(TRACE_LOG_PATH, "a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")

def clear_trace():
    """Clear the trace log by truncating the file (JSONL format)."""
    if os.path.exists(TRACE_LOG_PATH):
        with open(TRACE_LOG_PATH, "w", encoding="utf-8"):
            pass

print("✅ Helper functions upgraded.")

✅ Helper functions upgraded.

## Cell 7 — Steps 4–6: Main Pipeline Loop

In [17]:
# ============================================================
#  Steps 4-6 — Retrieval → LLM → Parse → Fill submission
# ============================================================

# Work on a copy of the template; iterate by id order from sample_submission
df_result = df_submission.copy()
df_result["answer"] = df_result["answer"].astype(object) 
q_lookup = df_questions.set_index("id")

clear_trace()

for idx, row in df_result.iterrows():
    q_id = int(row["id"])

    print(f"\n{'='*60}")
    print(f"[{idx+1}/{len(df_result)}] ID={q_id}")

    try:
        q_row    = q_lookup.loc[q_id]
        question = str(q_row["question"])
        choices  = [str(q_row[c]) for c in CHOICE_COLS]

        print(f"  ❓ {question[:80]}{'...' if len(question) > 80 else ''}")

        # --- Step 4: Retrieve ---
        retrieved           = retrieve_top_k(question)
        retrieved_filenames = [r["filename"] for r in retrieved]
        print(f"  📄 Retrieved: {retrieved_filenames}")

        # --- Step 5: LLM Generation ---
        prompt   = build_prompt(question, choices, retrieved)
        raw_resp = call_ollama(prompt)

        # --- Step 6: Parse ---
        think_text = extract_think(raw_resp)
        raw_answer = extract_final_answer(raw_resp)

        match_index = None
        is_fallback = False
        clean_raw = str(raw_answer).strip()

        # หาตัวเลข 1-10 จากผลลัพธ์ที่ extract มาได้
        numbers = re.findall(r'\b([1-9]|10)\b', clean_raw) 
        if numbers:
            match_index = int(numbers[0])
        else:
            match_index = 1 # Absolute fallback
            is_fallback = True

        # --- Explicit Print Logging ---
        if is_fallback:
            print(f"  ⚠️ FALLBACK (Defaulting to 1). Raw: '{str(raw_answer).strip()[:40]}...'")
        else:
            print(f"  🤖 Extracted Answer: {match_index}")

        # ---> รวบ append_trace ไว้ที่เดียว (1 ข้อ = 1 บรรทัดใน Log)
        append_trace({
            "question_id":     q_id,
            "question":        question,
            "retrieved_files": retrieved_filenames,
            "raw_response":    raw_resp,
            "think":           think_text,
            "final_answer":    match_index,
            "is_fallback":     is_fallback 
        })

        # Write the NUMBER into the submission DataFrame
        df_result.at[idx, "answer"] = int(match_index)

    except Exception as e:
        err_msg = str(e)
        print(f"  ❌ ERROR: {err_msg}")
        
        # กรณีเกิด Error ก็ Log แบบรวบยอดเช่นกัน
        append_trace({
            "question_id": q_id, 
            "error": err_msg,
            "is_fallback": True
        })

# --- Save timestamped submission CSV ---
timestamp   = datetime.now().strftime("%Y%m%d_%H%M%S")
output_path = os.path.join(SUBMISSION_DIR, f"submission_{timestamp}.csv")
df_result.to_csv(output_path, index=False, encoding="utf-8-sig")

print(f"\n✅ Done! Submission saved → {output_path}")
display(df_result)

============================================================
[1/100] ID=1
  ❓ Watch S3 Ultra กันน้ำได้กี่ ATM ครับ
  📄 Retrieved: ['products/WK-SW-001_wongkhojon_watch_s3_ultra.md (Chunk 3)', 'products/WK-SW-001_wongkhojon_watch_s3_ultra.md (Chunk 15)', 'products/WK-SW-001_wongkhojon_watch_s3_ultra.md (Chunk 16)', 'products/WK-SW-002_wongkhojon_watch_s3_pro.md (Chunk 16)']
  🤖 Extracted Answer: 5

============================================================
[2/100] ID=2
  ❓ ปากกา SaiFah Pen Gen 2 ราคาเท่าไหร่คะ
  📄 Retrieved: ['products/SF-TB-001_saifah_tab_s9_pro.md (Chunk 16)', 'products/JC-CS-006_judchuam_saifah_pen_gen2.md (Chunk 1)', 'products/SF-TB-005_saifah_tab_mini_7.md (Chunk 12)', 'products/JC-CS-006_judchuam_saifah_pen_gen2.md (Chunk 2)']
  🤖 Extracted Answer: 7

============================================================
[3/100] ID=3
  ❓ หูฟัง HeadPro X1 ใช้ Bluetooth เวอร์ชันอะไรคะ
  📄 Retrieved: ['products/KS-HP-001_kluensiang_headpro_x1.md (Chunk 10)', 'products/KS-HP-001_kluensiang_headpro_x1.md (Chunk 12)', 'products/KS-HP-002_kluensiang_headpro_x1_se.md (Chunk 2)', 'products/KS-HP-001_kluensiang_headpro_x1.md (Chunk 2)']
  🤖 Extracted Answer: 2

============================================================
[4/100] ID=4
  ❓ อยากเอามือถือเครื่องเก่ามาเทิร์น เปลี่ยนเป็นเครื่องใหม่ที่ฟ้าใหม่ได้ไหม?
  📄 Retrieved: ['store_info/general_faq.md (Chunk 11)']
  🤖 Extracted Answer: 6

============================================================
[5/100] ID=5
  ❓ สั่งของจากฟ้าใหม่ สั่งได้ครั้งละกี่ชิ้นครับ
  📄 Retrieved: ['store_info/general_faq.md (Chunk 2)', 'policies/cancellation_policy.md (Chunk 9)', 'policies/cancellation_policy.md (Chunk 1)', 'store_info/general_faq.md (Chunk 1)']
  🤖 Extracted Answer: 6

============================================================
[6/100] ID=6
  ❓ ฟ้าใหม่จ่ายด้วย crypto ได้มั้ยคะ เช่น Bitcoin
  📄 Retrieved: ['store_info/general_faq.md (Chunk 7)', 'store_info/general_faq.md (Chunk 6)']
  🤖 Extracted Answer: 8

============================================================
[7/100] ID=7
  ❓ ซื้อ AirBook 14 มาแล้ว อยากรู้ว่าในกล่องมีอะไรมาบ้าง
  📄 Retrieved: ['products/DN-LT-002_daonuea_airbook_14.md (Chunk 9)', 'products/DN-LT-003_daonuea_airbook_14_8gb.md (Chunk 9)', 'products/DN-LT-001_daonuea_airbook_15.md (Chunk 9)', 'products/DN-LT-003_daonuea_airbook_14_8gb.md (Chunk 13)']
  🤖 Extracted Answer: 1

============================================================
[8/100] ID=8
  ❓ DuoPad สั่งซื้อได้เลยไหมครับ หรือต้องพรีออเดอร์
  📄 Retrieved: ['products/SF-SP-011_saifah_phone_duopad.md (Chunk 18)', 'products/SF-SP-011_saifah_phone_duopad.md (Chunk 6)', 'products/SF-SP-011_saifah_phone_duopad.md (Chunk 14)', 'products/SF-SP-012_saifah_phone_pocketmini.md (Chunk 17)']
  🤖 Extracted Answer: 9

============================================================
[9/100] ID=9
  ❓ เฮ้ยย อ่านเยอะมากเลย ขอถามนิดนึงนะคะ คือพอดีว่าจะไปเที่ยวภูเก็ตกับเพื่อนสนิท 3 ค...
  📄 Retrieved: ['products/WK-FT-004_wongkhojon_ring_1.md (Chunk 16)', 'products/WK-SW-002_wongkhojon_watch_s3_pro.md (Chunk 16)', 'products/WK-SW-001_wongkhojon_watch_s3_ultra.md (Chunk 13)']
  🤖 Extracted Answer: 9

============================================================
[10/100] ID=10
  ❓ อยากใช้ซิม 2 ค่ายพร้อมกันครับ ใส่ซิมได้ 2 ใบมั้ย ไม่อยากพกมือถือ 2 เครื่อง มองอย...
  📄 Retrieved: ['products/SF-SP-001_saifah_phone_x9_pro_max.md (Chunk 20)', 'products/SF-SP-003_saifah_phone_x9.md (Chunk 13)', 'products/SF-SP-002_saifah_phone_x9_pro.md (Chunk 21)', 'products/SF-SP-002_saifah_phone_x9_pro.md (Chunk 20)']
  🤖 Extracted Answer: 9

============================================================
[11/100] ID=11
  ❓ โน้ตบุ๊คดาวเหนือ ครีเอเตอร์บุ๊ก 16 OLED ต่อจอเพิ่มได้กี่จอครับ อยากต่อ 2 จอ 4K ท...
  📄 Retrieved: ['products/DN-LT-014_daonuea_creatorbook_16_oled.md (Chunk 1)', 'products/DN-LT-014_daonuea_creatorbook_16_oled.md (Chunk 3)', 'products/DN-LT-014_daonuea_creatorbook_16_oled.md (Chunk 7)', 'products/DN-LT-017_daonuea_flexbook_detach.md (Chunk 3)']
  🤖 Extracted Answer: 5

============================================================
[12/100] ID=12
  ❓ จะซื้อโน้ตบุ๊คเล่น Genshin Impact ลื่นๆ กราฟิกสูงๆ มีรุ่นไหนตอบโจทย์บ้าง แล้วได้...
  📄 Retrieved: ['products/DN-LT-007_daonuea_stormbook_g7.md (Chunk 2)', 'products/DN-LT-007_daonuea_stormbook_g7.md (Chunk 15)', 'products/DN-LT-009_daonuea_stormbook_g5_2024.md (Chunk 3)', 'products/DN-LT-008_daonuea_stormbook_g5.md (Chunk 2)']
  🤖 Extracted Answer: 1

============================================================
[13/100] ID=13
  ❓ ทำงานในคาเฟ่เสียงดังมากเลย ต้องการหูฟังครอบหูที่ตัดเสียงรบกวนได้ดี แล้วก็ใช้สายโ...
  📄 Retrieved: ['products/KS-HP-001_kluensiang_headpro_x1.md (Chunk 2)', 'products/KS-EB-007_kluensiang_buds_open_ring.md (Chunk 13)', 'products/KS-HP-001_kluensiang_headpro_x1.md (Chunk 6)', 'products/KS-HP-002_kluensiang_headpro_x1_se.md (Chunk 5)']
  🤖 Extracted Answer: 6

============================================================
[14/100] ID=14
  ❓ ซื้อสายฟ้า X9 Pro มา อยากทราบว่าหัวชาร์จ 67W มาในกล่องด้วยเลยหรือต้องซื้อแยกคะ
  📄 Retrieved: ['products/JC-CH-001_judchuam_charger_67w_usbc.md (Chunk 3)', 'products/SF-SP-002_saifah_phone_x9_pro.md (Chunk 19)', 'products/SF-SP-002_saifah_phone_x9_pro.md (Chunk 16)', 'products/SF-SP-002_saifah_phone_x9_pro.md (Chunk 11)']
  🤖 Extracted Answer: 4

============================================================
[15/100] ID=15
  ❓ อยากฟังเพลง Lossless จาก streaming ได้คุณภาพดีๆ มีหูฟังครอบหูรุ่นไหนที่รองรับ LD...
  📄 Retrieved: ['products/KS-HP-001_kluensiang_headpro_x1.md (Chunk 3)', 'products/NT-EB-001_novatech_novabuds_pro.md (Chunk 12)', 'products/KS-HP-003_kluensiang_headon_700.md (Chunk 3)', 'products/KS-HP-005_kluensiang_headon_300.md (Chunk 2)']
  🤖 Extracted Answer: 7

============================================================
[16/100] ID=16
  ❓ อยากได้นาฬิกาที่วัดคลื่นหัวใจ ECG ได้ มีรุ่นไหนบ้างคะ แล้ว Watch S3 ตัวธรรมดามี ...
  📄 Retrieved: ['products/WK-SW-002_wongkhojon_watch_s3_pro.md (Chunk 15)', 'products/WK-SW-002_wongkhojon_watch_s3_pro.md (Chunk 3)', 'products/WK-SW-003_wongkhojon_watch_s3.md (Chunk 14)', 'products/WK-SW-008_wongkhojon_watch_s2_pro.md (Chunk 3)']
  🤖 Extracted Answer: 1

============================================================
[17/100] ID=17
  ❓ มองหาโน้ตบุ๊คเอาไว้ตัดต่อวิดีโอ 4K ครับ อยากได้จอสีแม่น แล้วก็พอร์ตอ่าน SD card ...
  📄 Retrieved: ['products/DN-LT-004_daonuea_probook_16.md (Chunk 13)', 'products/DN-LT-006_daonuea_probook_14_max.md (Chunk 13)', 'products/JC-HB-003_judchuam_dock_pro.md (Chunk 3)', 'products/DN-LT-005_daonuea_probook_14.md (Chunk 12)']
  🤖 Extracted Answer: 8

============================================================
[18/100] ID=18
  ❓ จะไปเที่ยวญี่ปุ่นช่วงสงกรานต์ หัวชาร์จ 67W ที่ซื้อไว้เอาไปใช้ที่ญี่ปุ่นได้มั้ยคร...
  📄 Retrieved: ['products/JC-CH-001_judchuam_charger_67w_usbc.md (Chunk 1)', 'products/JC-CH-001_judchuam_charger_67w_usbc.md (Chunk 2)']
  🤖 Extracted Answer: 9

============================================================
[19/100] ID=19
  ❓ แม่อายุ 70 แล้วครับ อยากหามือถือที่ใช้ง่ายๆ ตัวหนังสือใหญ่ มีปุ่มขอความช่วยเหลือ...
  📄 Retrieved: ['products/SF-SP-014_saifah_phone_senior_plus.md (Chunk 3)', 'products/SF-SP-014_saifah_phone_senior_plus.md (Chunk 11)', 'products/SF-SP-014_saifah_phone_senior_plus.md (Chunk 2)', 'products/SF-SP-014_saifah_phone_senior_plus.md (Chunk 7)']
  🤖 Extracted Answer: 2

============================================================
[20/100] ID=20
  ❓ ซื้อนาฬิกาไว้วิ่งมาราธอน อยากได้ตัวที่แบตอึด GPS แม่นๆ แล้วก็วิเคราะห์ฟอร์มวิ่งไ...
  📄 Retrieved: ['products/WK-FT-002_wongkhojon_band_8_pro.md (Chunk 3)', 'products/WK-SW-005_wongkhojon_watch_sport_g1.md (Chunk 3)', 'products/WK-FT-001_wongkhojon_band_8.md (Chunk 3)', 'products/WK-SW-003_wongkhojon_watch_s3.md (Chunk 4)']
  🤖 Extracted Answer: 2

============================================================
[21/100] ID=21
  ❓ ลูกชาย 8 ขวบอยากได้แท็บเล็ตเรียนออนไลน์ ครับ อยากได้ตัวที่ตกไม่แตกง่าย แล้วก็จำก...
  📄 Retrieved: ['products/SF-TB-006_saifah_tab_kid.md (Chunk 2)', 'products/DN-LT-013_daonuea_studybook_11.md (Chunk 2)', 'products/DN-LT-009_daonuea_stormbook_g5_2024.md (Chunk 3)', 'products/DN-LT-011_daonuea_studybook_14.md (Chunk 2)']
  🤖 Extracted Answer: 3

============================================================
[22/100] ID=22
  ❓ จอมือถือสายฟ้า X9 Pro แตกครับ ซ่อมได้มั้ย ถ้าซื้อ Care+ ไว้ ต้องจ่ายเพิ่มเท่าไหร...
  📄 Retrieved: ['products/SF-SP-001_saifah_phone_x9_pro_max.md (Chunk 15)', 'products/SF-SP-002_saifah_phone_x9_pro.md (Chunk 12)', 'products/SF-SP-002_saifah_phone_x9_pro.md (Chunk 13)', 'products/JC-CS-001_judchuam_case_clear_x9_pro.md (Chunk 1)']
  🤖 Extracted Answer: 8

============================================================
[23/100] ID=23
  ❓ Watch S3 กับ Watch S3 SE จอต่างกันยังไงคะ ใช้ AMOLED เหมือนกันไหม
  📄 Retrieved: ['products/WK-SW-003_wongkhojon_watch_s3.md (Chunk 2)', 'products/WK-SW-003_wongkhojon_watch_s3.md (Chunk 13)', 'products/WK-SW-004_wongkhojon_watch_s3_se.md (Chunk 2)', 'products/WK-SW-004_wongkhojon_watch_s3_se.md (Chunk 4)']
  🤖 Extracted Answer: 3

============================================================
[24/100] ID=24
  ❓ เปรียบเทียบแบตแล็ปท็อปหน่อย ดาวเหนือ แอร์บุ๊ก 14 กับ NovaTech SlimBook 14 ตัวไหน...
  📄 Retrieved: ['products/NT-LT-001_novatech_slimbook_14.md (Chunk 1)', 'products/NT-LT-001_novatech_slimbook_14.md (Chunk 2)', 'products/DN-LT-003_daonuea_airbook_14_8gb.md (Chunk 2)', 'products/DN-LT-002_daonuea_airbook_14.md (Chunk 1)']
  ⚠️ FALLBACK (Defaulting to 1). Raw: '<think>...'

============================================================
[25/100] ID=25
  ❓ NovaBuds Pro กับ บัดส์ Z5 Pro ประกันตัวไหนนานกว่ากันครับ
  📄 Retrieved: ['products/NT-EB-001_novatech_novabuds_pro.md (Chunk 11)', 'products/NT-EB-001_novatech_novabuds_pro.md (Chunk 3)', 'products/KS-EB-001_kluensiang_buds_z5_pro.md (Chunk 13)', 'products/NT-EB-001_novatech_novabuds_pro.md (Chunk 8)']
  🤖 Extracted Answer: 5

============================================================
[26/100] ID=26
  ❓ สนใจนาฬิกาวงโคจรครับ Watch S3 Pro กับ Watch S3 ตัวไหนมี ECG วัดคลื่นไฟฟ้าหัวใจได...
  📄 Retrieved: ['products/WK-SW-002_wongkhojon_watch_s3_pro.md (Chunk 15)', 'products/WK-SW-002_wongkhojon_watch_s3_pro.md (Chunk 3)', 'products/WK-SW-003_wongkhojon_watch_s3.md (Chunk 14)', 'products/WK-SW-008_wongkhojon_watch_s2_pro.md (Chunk 3)']
  🤖 Extracted Answer: 6

============================================================
[27/100] ID=27
  ❓ อยากได้หูฟังครอบหูตัดเสียงรบกวนค่ะ เฮดออน 500 กับ เฮดออน 300 ตัวไหนมี ANC คะ
  📄 Retrieved: ['products/KS-HP-004_kluensiang_headon_500.md (Chunk 2)', 'products/KS-HP-005_kluensiang_headon_300.md (Chunk 2)', 'products/KS-HP-003_kluensiang_headon_700.md (Chunk 5)', 'products/KS-HP-001_kluensiang_headpro_x1.md (Chunk 6)']
  🤖 Extracted Answer: 2

============================================================
[28/100] ID=28
  ❓ soundbar คลื่นเสียง SoundBar 300 กับ ArcWave SoundPillar 300 ระบบเสียงต่างกันยัง...
  📄 Retrieved: ['products/AW-SK-001_arcwave_soundpillar_300.md (Chunk 2)', 'products/AW-SK-001_arcwave_soundpillar_300.md (Chunk 3)', 'products/KS-SK-002_kluensiang_soundbar_300.md (Chunk 3)', 'products/KS-SK-002_kluensiang_soundbar_300.md (Chunk 2)']
  🤖 Extracted Answer: 7

============================================================
[29/100] ID=29
  ❓ แบนด์ 8 กับ 8 Pro ต่างกันยังไงเรื่อง GPS อ่ะคะ ตัวไหนมี GPS ในตัว?
  📄 Retrieved: ['products/WK-FT-001_wongkhojon_band_8.md (Chunk 3)', 'products/WK-FT-002_wongkhojon_band_8_pro.md (Chunk 2)', 'products/WK-SW-001_wongkhojon_watch_s3_ultra.md (Chunk 18)', 'products/WK-FT-002_wongkhojon_band_8_pro.md (Chunk 8)']
  🤖 Extracted Answer: 4

============================================================
[30/100] ID=30
  ❓ Hub 7-in-1 กับ Hub 4-in-1 ของจุดเชื่อม ชาร์จผ่าน USB-C ได้ทั้งสองตัวไหมครับ
  📄 Retrieved: ['products/JC-HB-002_judchuam_hub_usbc_4in1.md (Chunk 2)', 'products/JC-HB-001_judchuam_hub_usbc_7in1.md (Chunk 1)', 'products/JC-HB-002_judchuam_hub_usbc_4in1.md (Chunk 1)', 'products/JC-HB-001_judchuam_hub_usbc_7in1.md (Chunk 2)']
  🤖 Extracted Answer: 3

============================================================
[31/100] ID=31
  ❓ ซื้อวงโคจร Watch S3 Ultra ช่วง Mega Sale มาได้ 12 วันแล้วค่ะ ยังคืนได้อยู่ไหม
  📄 Retrieved: ['products/WK-SW-001_wongkhojon_watch_s3_ultra.md (Chunk 1)', 'products/WK-SW-001_wongkhojon_watch_s3_ultra.md (Chunk 11)', 'products/WK-SW-001_wongkhojon_watch_s3_ultra.md (Chunk 15)', 'policies/return_policy.md (Chunk 15)']
  🤖 Extracted Answer: 4

============================================================
[32/100] ID=32
  ❓ ช่วยดูให้หน่อยได้ไหมครับ เรื่องมันยาวนิดนึง คือผมอยากได้แล็ปท็อปสักเครื่องสำหรับ...
  📄 Retrieved: ['products/DN-LT-012_daonuea_studybook_14_plus.md (Chunk 1)', 'products/DN-LT-011_daonuea_studybook_14.md (Chunk 1)', 'products/DN-LT-003_daonuea_airbook_14_8gb.md (Chunk 2)', 'products/DN-LT-002_daonuea_airbook_14.md (Chunk 2)']
  🤖 Extracted Answer: 9

============================================================
[33/100] ID=33
  ❓ ครีเอเตอร์บุ๊ก 16 OLED เครื่องผมมีปัญหา อยากเคลมประกัน ให้มารับที่บ้านได้ป่าวครั...
  📄 Retrieved: ['products/DN-LT-014_daonuea_creatorbook_16_oled.md (Chunk 11)', 'products/DN-LT-014_daonuea_creatorbook_16_oled.md (Chunk 1)', 'products/DN-LT-014_daonuea_creatorbook_16_oled.md (Chunk 10)', 'products/DN-LT-004_daonuea_probook_16.md (Chunk 11)']
  🤖 Extracted Answer: 8

============================================================
[34/100] ID=34
  ❓ เคลมประกัน ArcWave SoundPillar 300 ต้องทำยังไงบ้างครับ ส่งซ่อมเองได้เลยมั้ย
  📄 Retrieved: ['products/AW-SK-001_arcwave_soundpillar_300.md (Chunk 9)', 'products/AW-SK-001_arcwave_soundpillar_300.md (Chunk 1)', 'products/AW-SK-001_arcwave_soundpillar_300.md (Chunk 2)', 'products/AW-SK-001_arcwave_soundpillar_300.md (Chunk 4)']
  🤖 Extracted Answer: 5

============================================================
[35/100] ID=35
  ❓ ซื้อเฟล็กซ์บุ๊ก Detach แบบ Bundle มา อยากคืนเฉพาะคีย์บอร์ดอย่างเดียวได้มั้ยคะ ไม...
  📄 Retrieved: ['products/DN-LT-018_daonuea_flexbook_detach_keyboard_bundle.md (Chunk 12)', 'products/DN-LT-017_daonuea_flexbook_detach.md (Chunk 12)', 'products/DN-LT-018_daonuea_flexbook_detach_keyboard_bundle.md (Chunk 11)', 'products/DN-LT-017_daonuea_flexbook_detach.md (Chunk 11)']
  🤖 Extracted Answer: 3

============================================================
[36/100] ID=36
  ❓ สั่งสายฟ้าโฟน X9 Pro ไปแล้ว ตอนนี้สถานะขึ้นว่าจัดส่งแล้ว อยากยกเลิกคำสั่งซื้อทำไ...
  📄 Retrieved: ['store_info/general_faq.md (Chunk 4)', 'policies/cancellation_policy.md (Chunk 4)', 'products/SF-SP-002_saifah_phone_x9_pro.md (Chunk 1)', 'policies/cancellation_policy.md (Chunk 1)']
  🤖 Extracted Answer: 2

============================================================
[37/100] ID=37
  ❓ สวัสดีค่ะ คืออยากปรึกษาเรื่องหูฟังที่ซื้อมาค่ะ เมื่อวันเสาร์ที่ผ่านมาไปร้านฟ้าให...
  📄 Retrieved: ['products/KS-EB-001_kluensiang_buds_z5_pro.md (Chunk 10)', 'products/KS-EB-002_kluensiang_buds_z5.md (Chunk 7)', 'products/KS-EB-008_kluensiang_buds_z5_pro_gold_limited.md (Chunk 7)', 'products/KS-EB-006_kluensiang_buds_z1.md (Chunk 2)']
  🤖 Extracted Answer: 8

============================================================
[38/100] ID=38
  ❓ เป็นสมาชิก Platinum อยู่ครับ สั่งสายฟ้า โฟน V7 ส่งแบบด่วนต้องจ่ายเพิ่มเท่าไหร่ ท...
  📄 Retrieved: ['products/SF-SP-005_saifah_phone_v7_lite.md (Chunk 2)', 'products/SF-SP-004_saifah_phone_v7.md (Chunk 1)', 'products/SF-SP-004_saifah_phone_v7.md (Chunk 11)', 'products/SF-SP-005_saifah_phone_v7_lite.md (Chunk 1)']
  🤖 Extracted Answer: 9

============================================================
[39/100] ID=39
  ❓ สั่ง Pre-order สายฟ้า โฟน DuoPad ไว้ กำหนดส่งวันที่ 15 เมษายน ตอนนี้วันที่ 14 เม...
  📄 Retrieved: ['products/SF-SP-011_saifah_phone_duopad.md (Chunk 20)', 'products/SF-SP-011_saifah_phone_duopad.md (Chunk 1)', 'products/SF-SP-011_saifah_phone_duopad.md (Chunk 13)', 'products/SF-SP-011_saifah_phone_duopad.md (Chunk 6)']
  🤖 Extracted Answer: 4

============================================================
[40/100] ID=40
  ❓ Watch S3 SE หน้าจอเป็น AMOLED ไหมครับ
  📄 Retrieved: ['products/WK-SW-003_wongkhojon_watch_s3.md (Chunk 2)', 'products/SF-SP-001_saifah_phone_x9_pro_max.md (Chunk 4)', 'products/SF-SP-002_saifah_phone_x9_pro.md (Chunk 4)', 'store_info/buying_guide_smartphones_2569.md (Chunk 8)']
  🤖 Extracted Answer: 9

============================================================
[41/100] ID=41
  ❓ เฟล็กซ์บุ๊ก Detach มีคีย์บอร์ดมาในกล่องไหมครับ
  📄 Retrieved: ['products/DN-LT-017_daonuea_flexbook_detach.md (Chunk 12)', 'products/DN-LT-018_daonuea_flexbook_detach_keyboard_bundle.md (Chunk 12)', 'products/DN-LT-017_daonuea_flexbook_detach.md (Chunk 11)', 'products/DN-LT-018_daonuea_flexbook_detach_keyboard_bundle.md (Chunk 8)']
  🤖 Extracted Answer: 7

============================================================
[42/100] ID=42
  ❓ เฮดออน 300 มีระบบตัดเสียง ANC ไหม
  📄 Retrieved: ['products/KS-HP-004_kluensiang_headon_500.md (Chunk 2)', 'products/KS-HP-005_kluensiang_headon_300.md (Chunk 2)', 'products/KS-HP-006_kluensiang_headon_300_fahmai_edition.md (Chunk 3)', 'products/KS-HP-003_kluensiang_headon_700.md (Chunk 2)']
  🤖 Extracted Answer: 2

============================================================
[43/100] ID=43
  ❓ หูฟัง StudioPro M1 เชื่อมต่อ Bluetooth ได้ไหมคะ
  📄 Retrieved: ['products/KS-HP-007_kluensiang_studiopro_m1.md (Chunk 2)', 'products/KS-HP-007_kluensiang_studiopro_m1.md (Chunk 7)', 'products/KS-HP-007_kluensiang_studiopro_m1.md (Chunk 1)', 'products/KS-HP-001_kluensiang_headpro_x1.md (Chunk 10)']
  🤖 Extracted Answer: 4

============================================================
[44/100] ID=44
  ❓ วงโคจร Band 8 มี GPS ในตัวไหมคะ
  📄 Retrieved: ['products/WK-FT-001_wongkhojon_band_8.md (Chunk 3)', 'products/WK-FT-002_wongkhojon_band_8_pro.md (Chunk 2)', 'products/WK-FT-001_wongkhojon_band_8.md (Chunk 2)', 'products/WK-FT-001_wongkhojon_band_8.md (Chunk 8)']
  🤖 Extracted Answer: 1

============================================================
[45/100] ID=45
  ❓ หูฟัง Z5 มีรุ่นไหนบ้างคะ?
  📄 Retrieved: ['products/KS-EB-002_kluensiang_buds_z5.md (Chunk 6)', 'products/KS-EB-002_kluensiang_buds_z5.md (Chunk 9)', 'products/KS-EB-001_kluensiang_buds_z5_pro.md (Chunk 8)', 'products/KS-EB-001_kluensiang_buds_z5_pro.md (Chunk 13)']
  🤖 Extracted Answer: 2

============================================================
[46/100] ID=46
  ❓ จอ 27 นิ้ว 4K มีรุ่นอะไรบ้างครับ?
  📄 Retrieved: ['products/AW-MN-001_arcwave_proview_27_4k.md (Chunk 2)', 'products/AW-MN-001_arcwave_proview_27_4k.md (Chunk 5)']
  🤖 Extracted Answer: 2

============================================================
[47/100] ID=47
  ❓ จอ 27 นิ้ว 4K ของดาวเหนือ ราคาเท่าไหร่คะ
  📄 Retrieved: ['products/DN-DT-004_daonuea_all_in_one_27.md (Chunk 1)', 'products/DN-DT-005_daonuea_all_in_one_24.md (Chunk 1)', 'products/DN-DT-004_daonuea_all_in_one_27.md (Chunk 2)', 'products/DN-LT-007_daonuea_stormbook_g7.md (Chunk 1)']
  🤖 Extracted Answer: 2

============================================================
[48/100] ID=48
  ❓ คลื่นเสียง 300 ราคาเท่าไหร่
  📄 Retrieved: ['products/KS-SK-002_kluensiang_soundbar_300.md (Chunk 1)', 'products/KS-SK-002_kluensiang_soundbar_300.md (Chunk 3)', 'products/KS-HP-005_kluensiang_headon_300.md (Chunk 1)', 'products/AW-SK-001_arcwave_soundpillar_300.md (Chunk 2)']
  🤖 Extracted Answer: 2

============================================================
[49/100] ID=49
  ❓ เฮดออน 300 มีสีอะไรบ้าง?
  📄 Retrieved: ['products/KS-HP-006_kluensiang_headon_300_fahmai_edition.md (Chunk 2)', 'products/KS-HP-005_kluensiang_headon_300.md (Chunk 1)', 'products/KS-HP-006_kluensiang_headon_300_fahmai_edition.md (Chunk 1)', 'products/KS-HP-006_kluensiang_headon_300_fahmai_edition.md (Chunk 7)']
  🤖 Extracted Answer: 6

============================================================
[50/100] ID=50
  ❓ แอร์บุ๊ก 14 RAM เท่าไหร่ครับ?

     id answer
0     1      5
1     2      7
2     3      2
3     4      6
4     5      6
..  ...    ...
95   96      9
96   97      1
97   98      1
98   99      9
99  100      3

[100 rows x 2 columns]

## Cell 8 — Sanity Check

In [18]:
# ============================================================
#  Sanity Check — submission stats & trace entries
# ============================================================

print(f"Total rows         : {len(df_result)}")
print(f"Answered (non-null): {df_result['answer'].notna().sum()}")
print(f"Still template val : {(df_result['answer'] == df_submission['answer']).sum()}")
print()
display(df_result)

with open(TRACE_LOG_PATH, "r", encoding="utf-8") as f:
    trace_lines = f.readlines()
print(f"\nTrace log entries: {len(trace_lines)}")

Total rows         : 100
Answered (non-null): 100
Still template val : 17

     id answer
0     1      5
1     2      7
2     3      2
3     4      6
4     5      6
..  ...    ...
95   96      9
96   97      1
97   98      1
98   99      9
99  100      3

[100 rows x 2 columns]

Trace log entries: 100